name = "Moded Minecraf"
author = "momo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a0caa3199043a9b9ea460acc37f18bb702cf15261abb8c58be6009310c4867c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
