name = "Moded Minecraf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b0f3e9def26ba88dde390f0d5ad2c4d01a5e7a131efa8456d3ff4664c84fd9c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
