name = "Moded Minecraf"
author = "momo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5c298a8c8f1ccc2438bca8b9635f0c91d736f715f4915d431d0818dd74f7e28"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "kubejs/data"
